---
- hosts: webserver
  become: yes

  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - docker.io
          - curl
          - wget
          - conntrack
        state: present

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        creates: /usr/local/bin/minikube

    - name: Start Minikube
      become_user: ubuntu
      shell: |
        minikube start --driver=docker
